name: nlzss
description: (De)compression with Nintendo's LZSS format.
version: 1.0.0
repository: https://github.com/phoenixr-codes/nlzss
homepage: https://github.com/phoenixr-codes/nlzss

executables:
  nlzss: nlzss

topics:
  - command-line
  - compression
  - nintendo

environment:
  sdk: ^3.4.0

dependencies:
  args: ^2.5.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
